import { Command, Option } from 'commander';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRootCommand } from '../src/root.js';
import type { Factory } from '../src/factory.js';

type ReferenceGroup = {
  slug: string;
  title: string;
  navTitle: string;
  description: string;
  commands: string[];
};

type CommandReference = {
  command: Command;
  path: string[];
};

type RenderedFile = {
  relativePath: string;
  content: string;
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cliRoot = path.resolve(__dirname, '..');
const workspaceRoot = path.resolve(cliRoot, '..');
const generatedHeader = '{/* Generated by cli/scripts/generate-cli-reference.ts. Do not edit by hand. */}';

const groups: ReferenceGroup[] = [
  {
    slug: 'auth',
    title: 'Auth Commands',
    navTitle: 'Authentication',
    description: 'Log in, inspect auth state, print tokens, and log out.',
    commands: ['auth'],
  },
  {
    slug: 'spaces',
    title: 'Space Commands',
    navTitle: 'Spaces',
    description: 'Create and manage spaces and their mounted environment.',
    commands: ['space'],
  },
  {
    slug: 'runtimes',
    title: 'Runtime Commands',
    navTitle: 'Runtimes',
    description: 'Create, start, stop, configure, and drive browser runtimes.',
    commands: ['runtime'],
  },
  {
    slug: 'runs',
    title: 'Run Commands',
    navTitle: 'Runs',
    description: 'Inspect run activity, events, files, live viewers, recordings, and invocations.',
    commands: ['run'],
  },
  {
    slug: 'files',
    title: 'File Commands',
    navTitle: 'Files',
    description: 'Upload, download, update, and delete durable files.',
    commands: ['file'],
  },
  {
    slug: 'vault',
    title: 'Vault Commands',
    navTitle: 'Vault',
    description: 'Store secrets, read values, and generate TOTP codes.',
    commands: ['vault'],
  },
  {
    slug: 'tools',
    title: 'Tool Commands',
    navTitle: 'Tools',
    description: 'Define tools, bundle toolsets, and inspect tool calls.',
    commands: ['tool', 'toolset', 'tool-call'],
  },
  {
    slug: 'ai',
    title: 'AI Commands',
    navTitle: 'AI',
    description: 'Discover managed models and manage BYOK AI credentials.',
    commands: ['ai'],
  },
  {
    slug: 'proxies',
    title: 'Proxy Commands',
    navTitle: 'Proxies',
    description: 'Manage proxies and browse managed proxy pools.',
    commands: ['proxy'],
  },
  {
    slug: 'extensions',
    title: 'Extension Commands',
    navTitle: 'Extensions',
    description: 'Upload, import, list, update, and delete browser extensions.',
    commands: ['browser-extension'],
  },
  {
    slug: 'account',
    title: 'Account Commands',
    navTitle: 'Account',
    description: 'Manage API keys, notification recipients, subaccounts, and usage.',
    commands: ['api-key', 'notification-recipient', 'subaccount', 'usage'],
  },
  {
    slug: 'help',
    title: 'Help Commands',
    navTitle: 'Help',
    description: 'Read operation-aware API, SDK, CLI, and MCP help.',
    commands: ['help', 'version'],
  },
];

const generatedPageNames = ['index', ...groups.map((group) => group.slug)];
const globallyDocumentedOptionFlags = new Set([
  '--json [fields]',
  '--jq <expression>',
  '--template <template>',
  '--params <json>',
  '--body <json>',
]);

function createDummyFactory(): Factory {
  return {
    version: '0.0.0',
    io: {
      in: process.stdin,
      out: process.stdout,
      err: process.stderr,
      isStdinTTY: () => false,
      isStdoutTTY: () => false,
      isStderrTTY: () => false,
      canPrompt: () => false,
      colorEnabled: () => false,
      writeOut: () => undefined,
      writeErr: () => undefined,
    },
    config: async () => {
      throw new Error('CLI reference generation must not load runtime config.');
    },
    apiClient: async () => {
      throw new Error('CLI reference generation must not create an API client.');
    },
  };
}

function commandByName(root: Command, name: string): Command {
  const command = root.commands.find((candidate) => candidate.name() === name);
  if (!command) throw new Error(`Unable to find CLI command ${name}`);
  return command;
}

function leafCommands(command: Command, commandPath: string[]): CommandReference[] {
  const visibleChildren = command.commands.filter((child) => !child.hidden);
  if (visibleChildren.length === 0) return [{ command, path: commandPath }];
  return visibleChildren.flatMap((child) => leafCommands(child, [...commandPath, child.name()]));
}

function commandSignature(reference: CommandReference): string {
  const args = registeredArguments(reference.command).map(argumentSyntax).join(' ');
  return ['bctrl', ...reference.path, args || '', hasVisibleCommandOptions(reference.command) ? '[flags]' : '']
    .filter(Boolean)
    .join(' ');
}

function registeredArguments(command: Command): Array<{
  name: () => string;
  required: boolean;
  variadic: boolean;
}> {
  const candidate = (command as unknown as { registeredArguments?: unknown }).registeredArguments;
  return Array.isArray(candidate)
    ? (candidate as Array<{ name: () => string; required: boolean; variadic: boolean }>)
    : [];
}

function argumentSyntax(argument: { name: () => string; required: boolean; variadic: boolean }): string {
  const suffix = argument.variadic ? '...' : '';
  const name = `${argument.name()}${suffix}`;
  return argument.required ? `<${name}>` : `[${name}]`;
}

function hasVisibleCommandOptions(command: Command): boolean {
  return command.options.some((option) => includeOption(option));
}

function includeOption(option: Option): boolean {
  if (option.hidden) return false;
  if (globallyDocumentedOptionFlags.has(option.flags)) return false;
  return true;
}

function optionDescription(option: Option): string {
  const choices = Array.isArray(option.argChoices) && option.argChoices.length > 0
    ? `. Choices: ${option.argChoices.map((choice) => `\`${choice}\``).join(', ')}.`
    : '';
  return `${option.description}${choices}`;
}

function renderOptionsTable(command: Command): string {
  const options = command.options.filter(includeOption);
  if (options.length === 0) return '';
  return [
    '| Flag | Description |',
    '| ---- | ----------- |',
    ...options.map(
      (option) =>
        `| \`${escapeTableCell(option.flags)}\` | ${escapeTableCell(optionDescription(option))} |`
    ),
  ].join('\n');
}

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, '<br />');
}

function commandAnchor(reference: CommandReference): string {
  return reference.path.join(' ');
}

function renderCommand(reference: CommandReference): string {
  const table = renderOptionsTable(reference.command);
  const parts = [
    `## \`bctrl ${commandAnchor(reference)}\``,
    '',
    reference.command.description() || 'Run this command.',
    '',
    '```bash',
    commandSignature(reference),
    '```',
    '',
  ];
  if (table) parts.push(table, '');
  return parts.join('\n');
}

function renderGroupPage(root: Command, group: ReferenceGroup): RenderedFile {
  const commandRefs = group.commands.flatMap((name) => {
    const command = commandByName(root, name);
    return leafCommands(command, [name]);
  });
  const frontmatter = [
    '---',
    `title: ${group.title}`,
    `description: ${group.description}`,
    `slug: /cli/reference/${group.slug}`,
    '---',
  ].join('\n');
  const content = [
    frontmatter,
    '',
    generatedHeader,
    '',
    group.description,
    '',
    'Output formatting flags (`--json`, `--jq`, and `--template`) are documented once in [Output Formatting](/cli/output) and are omitted from the tables below.',
    '',
    ...commandRefs.map(renderCommand),
    '',
  ].join('\n');
  return {
    relativePath: `fern/docs/pages/cli/reference/${group.slug}.mdx`,
    content: normalizeContent(content),
  };
}

function renderIndexPage(root: Command): RenderedFile {
  const topLevelCommands = root.commands.filter((command) => !command.hidden).map((command) => command.name());
  const frontmatter = [
    '---',
    'title: Command Reference',
    'description: The generated BCTRL CLI command reference.',
    'slug: /cli/reference',
    '---',
  ].join('\n');
  const content = [
    frontmatter,
    '',
    generatedHeader,
    '',
    'This reference is generated from the CLI command tree, so command names, arguments, and flags stay aligned with the installed `bctrl` binary.',
    '',
    'For command-specific help in a terminal, run:',
    '',
    '```bash',
    'bctrl --help',
    'bctrl <command> --help',
    'bctrl <command> <subcommand> --help',
    '```',
    '',
    '## Global output flags',
    '',
    'Most data commands return JSON by default and support these formatting flags:',
    '',
    '| Flag | Description |',
    '| ---- | ----------- |',
    '| `--json [fields]` | Output JSON with optional comma-separated field projection. |',
    '| `--jq <expression>` | Filter JSON output using a jq expression. |',
    '| `--template <template>` | Format JSON output using a Handlebars template. |',
    '| `--no-color` | Disable color output. |',
    '',
    'Pagination (`-L, --limit` and `--cursor`), confirmation (`-y, --yes`), and request override flags (`--params`, `--body`) appear on the generated command pages where supported.',
    '',
    '## Command groups',
    '',
    '| Group | Commands | Description |',
    '| ----- | -------- | ----------- |',
    ...groups.map(
      (group) =>
        `| [${group.navTitle}](/cli/reference/${group.slug}) | ${group.commands.map((command) => `\`${command}\``).join(', ')} | ${group.description} |`
    ),
    '',
    '## Top-level commands',
    '',
    topLevelCommands.map((command) => `\`${command}\``).join(', '),
    '',
  ].join('\n');
  return {
    relativePath: 'fern/docs/pages/cli/reference/index.mdx',
    content: normalizeContent(content),
  };
}

function normalizeContent(value: string): string {
  return value.replace(/\r\n/g, '\n').replace(/[ \t]+$/gm, '').replace(/\n{3,}/g, '\n\n');
}

function renderFiles(): RenderedFile[] {
  const root = createRootCommand(createDummyFactory());
  return [renderIndexPage(root), ...groups.map((group) => renderGroupPage(root, group))];
}

async function pathExists(candidate: string): Promise<boolean> {
  try {
    await fs.access(candidate);
    return true;
  } catch {
    return false;
  }
}

async function docsRoots(): Promise<string[]> {
  const docsRoot = path.join(workspaceRoot, 'platform-docs');
  if (!(await pathExists(path.join(docsRoot, 'fern', 'versions', 'latest.yml')))) {
    throw new Error('Unable to find platform-docs.');
  }
  return [docsRoot];
}

function referenceNavBlock(): string {
  return [
    '      - section: Reference',
    '        contents:',
    '          - page: Command Reference',
    '            path: ../docs/pages/cli/reference/index.mdx',
    '            icon: fa-duotone fa-list',
    ...groups.flatMap((group) => [
      `          - page: ${group.navTitle}`,
      `            path: ../docs/pages/cli/reference/${group.slug}.mdx`,
    ]),
  ].join('\n');
}

function replaceCliReferenceNav(source: string): string {
  const start = source.indexOf('      - section: Reference\n        contents:\n          - page: Command Reference\n            path: ../docs/pages/cli/reference/index.mdx');
  if (start < 0) throw new Error('Unable to find CLI Reference navigation block.');
  const nextTab = source.indexOf('\n  - tab: mcp', start);
  if (nextTab < 0) throw new Error('Unable to find end of CLI navigation block.');
  return `${source.slice(0, start)}${referenceNavBlock()}${source.slice(nextTab)}`;
}

async function writeGeneratedFiles(baseDir: string, files: RenderedFile[]): Promise<void> {
  const referenceDir = path.join(baseDir, 'fern', 'docs', 'pages', 'cli', 'reference');
  await fs.mkdir(referenceDir, { recursive: true });
  const existing = await fs.readdir(referenceDir).catch(() => []);
  for (const name of existing) {
    if (name.endsWith('.mdx') && generatedPageNames.includes(name.replace(/\.mdx$/, ''))) continue;
    if (name.endsWith('.mdx')) await fs.rm(path.join(referenceDir, name), { force: true });
  }
  for (const file of files) {
    const target = path.join(baseDir, file.relativePath);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, file.content, 'utf8');
  }
  const navPath = path.join(baseDir, 'fern', 'versions', 'latest.yml');
  const nav = await fs.readFile(navPath, 'utf8');
  await fs.writeFile(navPath, normalizeContent(replaceCliReferenceNav(nav)), 'utf8');
}

async function checkGeneratedFiles(baseDir: string, files: RenderedFile[]): Promise<string[]> {
  const mismatches: string[] = [];
  for (const file of files) {
    const target = path.join(baseDir, file.relativePath);
    const actual = await fs.readFile(target, 'utf8').catch(() => null);
    if (actual === null) mismatches.push(`${path.relative(baseDir, target)} is missing`);
    else if (normalizeContent(actual) !== file.content) mismatches.push(`${path.relative(baseDir, target)} is stale`);
  }
  const navPath = path.join(baseDir, 'fern', 'versions', 'latest.yml');
  const nav = await fs.readFile(navPath, 'utf8');
  const expectedNav = normalizeContent(replaceCliReferenceNav(nav));
  if (normalizeContent(nav) !== expectedNav) mismatches.push('fern/versions/latest.yml is stale');

  const referenceDir = path.join(baseDir, 'fern', 'docs', 'pages', 'cli', 'reference');
  const existing = await fs.readdir(referenceDir).catch(() => []);
  for (const name of existing) {
    if (name.endsWith('.mdx') && !generatedPageNames.includes(name.replace(/\.mdx$/, ''))) {
      mismatches.push(`fern/docs/pages/cli/reference/${name} is obsolete`);
    }
  }
  return mismatches;
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check');
  const files = renderFiles();
  const roots = await docsRoots();

  if (checkMode) {
    const mismatches = (await Promise.all(roots.map((root) => checkGeneratedFiles(root, files)))).flat();
    if (mismatches.length > 0) {
      for (const mismatch of mismatches) console.error(mismatch);
      console.error('Run `pnpm generate:cli-reference` from the cli repo.');
      process.exit(1);
    }
    console.log('CLI reference docs are up to date.');
    return;
  }

  for (const root of roots) {
    await writeGeneratedFiles(root, files);
    console.log(`Generated CLI reference docs in ${path.relative(workspaceRoot, root) || root}`);
  }
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
